/// Suitable bingo calls. Code supplied by Chat GPT.
const bingoNumbers = [
  'Kelly\'s Eye - 1',
  'One Little Duck - 2',
  'Cup of Tea - 3',
  'Knock at the Door - 4',
  'Man Alive - 5',
  'Half a Dozen - 6',
  'Lucky Seven - 7',
  'Garden Gate - 8',
  'Doctor\'s Orders - 9',
  'Prime Minister\'s Den - 10',
  'Legs Eleven - 11',
  'One Dozen - 12',
  'Unlucky for Some - 13',
  'Valentine\'s Day - 14',
  'Young and Keen - 15',
  'Sweet Sixteen - 16',
  'Dancing Queen - 17',
  'Coming of Age - 18',
  'Goodbye-Teens - 19',
  'One Score - 20',
  'Key of the Door - 21',
  'Two Little Ducks - 22',
  'Thee and Me - 23',
  'Two Dozen - 24',
  'Duck and Dive - 25',
  'Pick and Mix - 26',
  'Gateway to Heaven - 27',
  'Over Weight - 28',
  'Rise and Shine - 29',
  'Dirty Gertie - 30',
  'Get Up and Run - 31',
  'Buckle My Shoe - 32',
  'Dirty Knee - 33',
  'Ask for More - 34',
  'Jump and Jive - 35',
  'Three Dozen - 36',
  'More than Eleven - 37',
  'Christmas Cake - 38',
  'Steps - 39',
  'Life Begins - 40',
  'Time for Fun - 41',
  'Winnie the Pooh - 42',
  'Down on Your Knees - 43',
  'Droopy Drawers - 44',
  'Halfway There - 45',
  'Up to Tricks - 46',
  'Four and Seven - 47',
  'Four Dozen - 48',
  'PC - 49',
  'Half a Century - 50',
  'Tweak of the Thumb - 51',
  'Danny La Rue - 52',
  'Here Comes Herbie - 53',
  'Clean the Floor - 54',
  'Snakes Alive - 55',
  'Was She Worth It? - 56',
  'Heinz Varieties - 57',
  'Make Them Wait - 58',
  'Brighton Line - 59',
  'Five Dozen - 60',
  'Baker\'s Bun - 61',
  'Turn the Screw - 62',
  'Tickle Me 63 - 63',
  'Red Raw - 64',
  'Old Age Pension - 65',
  'Clickety Click - 66',
  'Made in Heaven - 67',
  'Saving Grace - 68',
  'Either Way Up - 69',
  'Three Score and Ten - 70',
  'Bang on the Drum - 71',
  'Six Dozen - 72',
  'Queen Bee - 73',
  'Candy Store - 74',
  'Strive and Strive - 75',
  'Trombones - 76',
  'Sunset Strip - 77',
  'Heaven\'s Gate - 78',
  'One More Time - 79',
  'Eight and Blank - 80',
  'Stop and Run - 81',
  'Straight On Through - 82',
  'Time for Tea - 83',
  'Seven Dozen - 84',
  'Staying Alive - 85',
  'Between the Sticks - 86',
  'Torquay in Devon - 87',
  'Two Fat Ladies - 88',
  'Nearly There - 89',
  'Top of the Shop - 90'
];
